# Param Config for HDPSM and DART

selection_params:
  boosting: dart
  objective: binary
  metric: 
    - binary_logloss
    - auc  
  drop_rate: 0.1
  drop_seed: 1
  max_drop: 5
  num_leaves: 31
  max_depth: 5     
  max_bin: 255
  min_data_in_leaf: 81
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.4 
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

hdpsm_params:
  boosting_type: gbdt
  objective: binary
  metric:
    - binary_logloss
    - auc
  num_leaves: 40
  max_depth: 6
  max_bin: 255
  min_data_in_leaf: 101
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.4
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4