# 💡 This is the best training params for different protein sequence length.
7aa:
  boosting_type: gbdt
  objective: binary
  metric:
    - binary_logloss 
    - auc
  num_leaves: 25
  max_depth: 5
  max_bin: 95
  min_data_in_leaf: 31
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.0
  lambda_l2: 1e-5
  min_split_gain: 0.2
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

17aa:
  boosting_type: gbdt
  objective: binary
  metric:
    - binary_logloss 
    - auc  
  num_leaves: 30
  max_depth: 5
  max_bin: 255
  min_data_in_leaf: 101
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.4
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

27aa:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc  
  num_leaves: 25
  max_depth: 6
  max_bin: 115
  min_data_in_leaf: 101
  learning_rate: 0.01
  feature_fraction: 0.7
  bagging_fraction: 0.6
  bagging_freq: 20
  lambda_l1: 0.001
  lambda_l2: 0.001
  min_split_gain: 0.3
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

37aa:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc  
  num_leaves: 10
  max_depth: 5
  max_bin: 5
  min_data_in_leaf: 91
  learning_rate: 0.01
  feature_fraction: 0.6
  bagging_fraction: 0.8
  bagging_freq: 20
  lambda_l1: 0.1
  lambda_l2: 0.6
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

47aa:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc  
  num_leaves: 5
  max_depth: 3
  max_bin: 195
  min_data_in_leaf: 41
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.0
  min_split_gain: 1.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

57aa:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc  
  num_leaves: 20
  max_depth: 5
  max_bin: 115
  min_data_in_leaf: 11
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 1e-05
  lambda_l2: 0.6
  min_split_gain: 0.6
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

67aa:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc  
  num_leaves: 30
  max_depth: 5
  max_bin: 225
  min_data_in_leaf: 101
  learning_rate: 0.01
  feature_fraction: 0.7
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 1e-05
  lambda_l2: 0.001
  min_split_gain: 0.8
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

# 💡 train params for DART to run lightGBM
selection_params:
  boosting: dart
  objective: binary
  metric: 
    - binary_logloss
    - auc
  drop_rate: 0.1
  drop_seed: 1
  max_drop: 3
  num_leaves: 7
  max_depth: 3 
  max_bin: 255
  min_data_in_leaf: 61
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.4
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

