# 💡 This is the best training params for different RNA sequence length.
21bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc
  num_leaves: 5
  max_depth: 7
  max_bin: 245
  min_data_in_leaf: 51
  learning_rate: 0.01
  feature_fraction: 0.9
  bagging_fraction: 0.9
  bagging_freq: 15
  lambda_l1: 0.0
  lambda_l2: 0.0
  min_split_gain: 1.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

51bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc
  num_leaves: 95
  max_depth: 5
  max_bin: 245
  min_data_in_leaf: 41
  learning_rate: 0.01
  feature_fraction: 0.8
  bagging_fraction: 0.9
  bagging_freq: 10
  lambda_l1: 0.9
  lambda_l2: 0.4
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

81bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc
  num_leaves: 5
  max_depth: 7
  max_bin: 195
  min_data_in_leaf: 51
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 0.8
  bagging_freq: 45
  lambda_l1: 1.0
  lambda_l2: 0.0
  min_split_gain: 0.2
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

111bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc
  num_leaves: 10
  max_depth: 6
  max_bin: 255
  min_data_in_leaf: 51
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.0
  lambda_l2: 0.001
  min_split_gain: 0.6
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

141bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss
    - auc
  num_leaves: 20
  max_depth: 6
  max_bin: 75
  min_data_in_leaf: 11
  learning_rate: 0.08
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 1.0
  lambda_l2: 1.0
  min_split_gain: 0.3
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

171bp:
  boosting_type: gbdt
  objective: binary
  metric:
    - binary_logloss 
    - auc
  num_leaves: 40
  max_depth: 7
  max_bin: 125
  min_data_in_leaf: 61
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.5
  lambda_l2: 0.9
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

201bp:
  boosting_type: gbdt
  objective: binary
  metric: 
    - binary_logloss 
    - auc
  num_leaves: 10
  max_depth: 5
  max_bin: 195
  min_data_in_leaf: 51
  learning_rate: 0.01
  feature_fraction: 0.6
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.5
  lambda_l2: 0.7
  min_split_gain: 0.1
  verbosity: -1
  is_unbalance: False
  n_jobs: 4

# 💡 train params for DART to run lightGBM
selection_params:
  boosting: dart
  objective: binary
  metric: 
    - binary_logloss
    - auc
  drop_rate: 0.1
  drop_seed: 1
  max_drop: 4
  num_leaves: 15
  max_depth: 4  
  max_bin: 255
  min_data_in_leaf: 51
  learning_rate: 0.01
  feature_fraction: 1.0
  bagging_fraction: 1.0
  bagging_freq: 45
  lambda_l1: 0.001
  lambda_l2: 0.4
  min_split_gain: 0.0
  verbosity: -1
  is_unbalance: False
  n_jobs: 4